controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"

    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

    gripper_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

joint_trajectory_controller:
  ros__parameters:
    joints:
      - fingrip_joint1
      - fingrip_joint2
      - fingrip_joint3
      - fingrip_joint4
      - fingrip_joint5
      - fingrip_joint6
      - fingrip_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_trajectory_controller:
  ros__parameters:
    joints:
      - fingrip_finger1_base_joint
      - fingrip_finger1_proximal_joint
      - fingrip_finger2_base_joint
      - fingrip_finger2_proximal_joint
      - fingrip_finger3_proximal_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
