controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"

    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

    gripper_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

joint_trajectory_controller:
  ros__parameters:
    joints:
      - fingrip_joint1
      - fingrip_joint2
      - fingrip_joint3
      - fingrip_joint4
      - fingrip_joint5
      - fingrip_joint6
      - fingrip_joint7

    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      fingrip_joint1:
        p: 4000.0
        d: 10.0
        i: 250.0
        i_clamp: 15.0
      fingrip_joint2:
        p: 10000.0
        d: 25.0
        i: 600.0
        i_clamp: 45.0
      fingrip_joint3:
        p: 8000.0
        d: 20.0
        i: 450.0
        i_clamp: 30.0
      fingrip_joint4:
        p: 6000.0
        d: 15.0
        i: 300.0
        i_clamp: 30.0
      fingrip_joint5:
        p: 3000.0
        d: 5.0
        i: 175.0
        i_clamp: 7.0
      fingrip_joint6:
        p: 2500.0
        d: 3.0
        i: 150.0
        i_clamp: 6.0
      fingrip_joint7:
        p: 2000.0
        d: 2.0
        i: 10.0
        i_clamp: 5.0

gripper_trajectory_controller:
  ros__parameters:
    joints:
      - fingrip_finger1_base_joint
      - fingrip_finger2_base_joint
      - fingrip_finger1_proximal_joint
      - fingrip_finger2_proximal_joint
      - fingrip_finger3_proximal_joint
      - fingrip_finger1_intermediaire_joint
      - fingrip_finger2_intermediaire_joint
      - fingrip_finger3_intermediaire_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      fingrip_finger1_base_joint:
        p: 225.0
        d: 0.001
        i: 0.4
        i_clamp: 4.0
      fingrip_finger2_base_joint:
        p: 225.0
        d: 0.001
        i: 0.4
        i_clamp: 4.0
      fingrip_finger1_proximal_joint:
        p: 225.0
        d: 0.001
        i: 0.4
        i_clamp: 4.0
      fingrip_finger2_proximal_joint:
        p: 225.0
        d: 0.001
        i: 0.4
        i_clamp: 4.0
      fingrip_finger3_proximal_joint:
        p: 225.0
        d: 0.001
        i: 0.4
        i_clamp: 4.0
      fingrip_finger1_intermediaire_joint:
        p: 225.0
        d: 0.001
        i: 0.4
        i_clamp: 4.0
      fingrip_finger2_intermediaire_joint:
        p: 225.0
        d: 0.001
        i: 0.4
        i_clamp: 4.0
      fingrip_finger3_intermediaire_joint:
        p: 225.0
        d: 0.001
        i: 0.4
        i_clamp: 4.0
