controller_names:
  - joint_trajectory_controller
  - gripper_trajectory_controller
  # - gripper_action_controller

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - fingrip_joint1
    - fingrip_joint2
    - fingrip_joint3
    - fingrip_joint4
    - fingrip_joint5
    - fingrip_joint6
    - fingrip_joint7

gripper_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - fingrip_finger1_base_joint
    - fingrip_finger1_proximal_joint
    - fingrip_finger2_base_joint
    - fingrip_finger2_proximal_joint
    - fingrip_finger3_proximal_joint
    - fingrip_finger1_intermediaire_joint
    - fingrip_finger2_intermediaire_joint
    - fingrip_finger3_intermediaire_joint

# ----- Gripper action controller (not yet functional)
# gripper_action_controller:
#   action_ns: gripper_cmd
#   type: GripperCommand
#   default: true
#   joints:
#     - fingrip_finger_joint1
#
# Note: Once implemented, the following config needs to be within controller parameters
# controller_manager:
#   ros__parameters:
#     gripper_action_controller:
#       type: position_controllers/GripperActionController
# gripper_action_controller:
#   ros__parameters:
#     joint: fingrip_finger_joint1
#
# Node: Remember to enable mimicking of finger joints before attempting to use gripper action
