nb-fingers: 2
joints:
  - /right_driver_j
  - /left_driver_j
limit:
  lower:
    - -90
    - -90
  upper:
    - -46
    - -46
abduction: 
  activated:
    - false
    - false
  limit:
    lower:
      - null
      - null
    upper:
      - null
      - null
