# Locations of robot resources
description_package : fingrip_description # If true, use simulated clock.
PP_package : fingrip_pp_config # Custom package that handle simulation

# Locations of results files
#! Now, the file path will be saved in the package my_training_result (!in the share path for now!)
#! Avoiding to change the path everytime I change my computer

# Robot selection
robot_type : IRB140 # Name of the robot type to use. {IRB140} #WIP

# Gripper selection
gripper_type: robotiq # {robotiq, finrip} #WIP
gripper_model: Robotiq-2F-140

# Object selection
object_type : renfort1 # Object that we will test it out

# IHM
ihm_training_package : ihm_training
ihm_explore_package : ihm_explore
ihm_log_level : warn

# Simulation
simulator_log_level : info # The level of logging that is applied to all ROS 2 nodes launched by this script. [debug,info,warn]
use_sim_time : true # If true, use simulated clock.
number_of_parallel_node : 5
headless_mode : true

# Miscellaneous
number_of_primitives : 20 # Using this parameter to compare primitive with generated grasps, only for analysis purpose
training : QGG # HGG or QGG for latent space exploration
debug : false
