# Locations of robot resources
description_package : fingrip_description # If true, use simulated clock.
scene : robotiq-assembly-V7.ttt # Name or filepath of model to load
PP_package : fingrip_pp_config # Custom package that handle simulation

# Locations of results files
result_file_path : /home/alex/additive_manufacturing/result # Folder the data from the grasp capture will be saved

# Robot selection
robot_type : fingrip # Name of the robot type to use.

# Object selection
object_type : renfort1 # Object that we will test it out

# IHM
ihm_training_package : ihm_training
ihm_explore_package : ihm_explore

# Miscellaneous
simulator_log_level : info # The level of logging that is applied to all ROS 2 nodes launched by this script.
ihm_log_level : warn
use_sim_time : true # If true, use simulated clock.