initial_joint_positions:
  fingrip_arm:
    joint1: 0.0
    joint2: 0.0
    joint3: 0.0
    joint4: 0.0
    joint5: 0.0
    joint6: 0.0
    joint7: 0.0
  fingrip_gripper:
    finger1:
      base_joint: 0.0
    finger2:
      base_joint: 0.0
    finger3:
      base_joint: 0.0