initial_joint_positions:
  fingrip_arm:
    joint1: 1.884 # 108°
    joint2: -0.6105 # -35°
    joint3: 2.7038 # 154°
    joint4: 1.535 # 88°
    joint5: -1.256 # -72°
    joint6: -1.744 # -100°
    joint7: -2.1816 # -125°
  fingrip_gripper:
    finger1:
      base_joint: 0.0
      proximal_joint: 0.0
      intermediaire_joint: 0.0
      distal_joint: 0.0
    finger2:
      base_joint: 0.0
      proximal_joint: 0.0
      intermediaire_joint: 0.0
      distal_joint: 0.0
    finger3:
      base_joint: 0.0
      proximal_joint: 0.0
      intermediaire_joint: 0.0
      distal_joint: 0.0
    finger4:
      base_joint: 0.0
      proximal_joint: 0.0
      intermediaire_joint: 0.0
      distal_joint: 0.0