renfort1: 
  offset_pos:
    x: 0
    y: 0
    z: 0
  offset_rot:
    r: 0
    p: 0
    y: 0
#  model_file: "piece_burr_collision_with_plane.stl"
  model_file: "renfort_1.ttm"
  scale:
    - 0.001
    - 0.001
    - 0.001
  pose_type:
    r:
      - 0.0
    p:
      - 0.0
    z:
#      - 0.70107
      - 0.761
    sym_ax_z:
      - false
coude:
  offset_pos:
    x: -0.003996
    y: -0.01787591
    z: -0.00133297
  offset_rot:
    r: 0.00027054006212198913
    p: -0.00873299329306388
    y: -0.05011673865631564
  model_file: "coude.ttm"
  scale:
    - 0.001
    - 0.001
    - 0.001
  pose_type:
    r:
      - 0.3358 # 19.24
      - rad(-pi/2) # -90
    p:
      - 0.0
      - 0.979 # 56.093
    z:
      - 0.692
      - 0.733
    sym_ax_z:
      - false
      - false