renfort1: 
  offset_pos: # (m)
    x: 0.65
    y: -0.07
    z: 0.13
  offset_rot: # (rad)
    r: 0
    p: -0.46 # -26.35605
    y: 0
  model_file: "renfort_1.ttm"
  scale:
    - 0.001
    - 0.001
    - 0.001
  pose_type:
    r: # (rad)
      - 0.0
      - 3.14
    p: #  (rad)
      - -0.46
      - 0.79
    z: # m
      - 0.13
      - 0.14
    sym_ax_z:
      - false
coude:
  offset_pos: # (m)
    x: 0.745
    y: 0.01
    z: 0.25
  offset_rot: # (rad)
    r: 2.855 # 2.37
    p: -1.03 # -0.75
    y: 2.853 # 0.2
  model_file: "coude.ttm"
  scale:
    - 0.001
    - 0.001
    - 0.001
  pose_type:
    r:
      - 2.855
    p:
      - -1.03
    z:
      - 0.25
    sym_ax_z:
      - false
      - false