renfort1: 
  offset_pos: # (m)
    x: 0.5
    y: -0.07
    z: 0.13
  offset_rot: # (rad)
    r: 0
    p: -0.46 # -26.35605
    y: 0
  model_file: "renfort_1.ttm"
  scale:
    - 0.001
    - 0.001
    - 0.001
  pose_type:
    r: # (rad)
      - 0.0
      - 3.14
    p: #  (rad)
      - 0.46
      - 0.79
    z: # m
      - 0.13
      - 0.14
    sym_ax_z:
      - false
coude:
  offset_pos: # (m)
    x: 0.6005
    y: 0.08576
    z: 0.20256
  offset_rot: # (rad)
    r: 2.3146 #132.62
    p: -0.74611 # -42.749
    y: 2.16738 # +124.182
  model_file: "coude.ttm"
  scale:
    - 0.001
    - 0.001
    - 0.001
  pose_type:
    r:
      - 2.3146
    p:
      - -0.74611
    z:
      - 0.20256
    sym_ax_z:
      - false
      - false