renfort1: 
  offset_pos: # (m)
    x: 0.5
    y: -0.07
    z: 0.13
  offset_rot: # (rad)
    alpha: 0
    beta: -0.46
    gamma: 0
  model_file: "renfort_1.ttm"
  scale:
    - 0.001
    - 0.001
    - 0.001
  pose_type:
    alpha: # (rad)
      - 0.0
    beta: #  (rad)
      - 0.46
    z: # m
      - 0.13
    sym_ax_z:
      - false
coude:
  offset_pos: # (m)
    x: 0.6005
    y: 0.08576
    z: 0.20256
  offset_rot: # (rad)
    alpha: 2.3146 #132.62
    beta: -0.74611 # -42.749
    gamma: 2.16738 # +124.182
  model_file: "coude.ttm"
  scale:
    - 0.001
    - 0.001
    - 0.001
  pose_type:
    alpha:
      - 2.3146
    beta:
      - -0.74611
    z:
      - 0.20256
    sym_ax_z:
      - false
      - false