ipfapieceburr:
  offset_pos:
    x: 0
    y: 0
    z: 0
  offset_rot:
    r: 0
    p: 0
    y: 0
#  model_file: "piece_burr_collision_with_plane.stl"
  model_file: "piece_burr_collision.stl"
  scale:
    - 0.001
    - 0.001
    - 0.001
  pose_type:
    r:
      - 0.0
    p:
      - 0.0
    z:
#      - 0.70107
      - 0.761
    sym_ax_z:
      - false
ipfapiece:
  offset_pos:
    x: 0
    y: 0
    z: 0
  offset_rot:
    r: 0
    p: 0
    y: 0
  model_file: "piece_collision.stl"
  scale:
    - 0.001
    - 0.001
    - 0.001
  pose_type:
    r:
      - 0.0
    p:
      - 0.0
    z:
      - 0.68839
    sym_ax_z:
      - false
ipfa:
  offset_pos:
    x: 0
    y: 0
    z: 0
  offset_rot:
    r: 0
    p: 0
    y: 0
  model_file: "piece_plateau_collision.stl"
  scale:
    - 0.001
    - 0.001
    - 0.001
  pose_type:
    r:
      - 0.0
    p:
      - 0.0
    z:
      - 0.654
    sym_ax_z:
      - false
coude:
  offset_pos:
    x: -0.003996
    y: -0.01787591
    z: -0.00133297
  offset_rot:
    r: 0.00027054006212198913
    p: -0.00873299329306388
    y: -0.05011673865631564
  model_file: "coude100_rototrans_singleface_simplified.stl"
  scale:
    - 0.001
    - 0.001
    - 0.001
  pose_type:
    r:
      - 0.3358
      - rad(-pi/2)
    p:
      - 0.0
      - 0.979
    z:
      - 0.692
      - 0.733
    sym_ax_z:
      - false
      - false
poulie:
  offset_pos:
    x: 0.0
    y: 0.0
    z: 0.0
  offset_rot:
    r: 0.0
    p: 0.0
    y: 0.0
  model_file: "poulie.stl"
  scale:
    - 0.0006
    - 0.0006
    - 0.0009
  pose_type:
    r:
      - 0.0
      - rad(pi/2)
    p:
      - 0.0
      - -0.303
    z:
      - 0.640
      - 0.707
    sym_ax_z:
      - true
      - false
cannette:
  offset_pos:
    x: 0.003937
    y: 0.0047244
    z: -0.18
  offset_rot:
    r: 0.0
    p: 0.0
    y: 0.0
  model_file: "cannette.stl"
  scale:
    - 0.001
    - 0.001
    - 0.001
  pose_type:
    r:
      - 0.0
      - rad(pi/2)
      - rad(pi)
    p:
      - 0.0
      - 0.052
      - 0.0
    z:
      - 0.637
      - 0.672
      - 0.766
    sym_ax_z:
      - true
      - false
      - true
parpaing:
  offset_pos:
    x: 0.0
    y: 0.0
    z: 0.0
  offset_rot:
    r: 0.0
    p: 0.0
    y: 0.0
  model_file: "parpaing.stl"
  scale:
    - 0.01
    - 0.01
    - 0.01
  pose_type:
    r:
      - 0.0
      - rad(pi/2)
      - 0.0
    p:
      - 0.0
      - 0.0
      - rad(pi/2)
    z:
      - 0.640
      - 0.679
      - 0.725
    sym_ax_z:
      - false
      - false
      - false
parpaing_z1-1:
  offset_pos:
    x: 0.0
    y: 0.0
    z: 0.0
  offset_rot:
    r: 0.0
    p: 0.0
    y: 0.0
  model_file: "parpaing_z1-1.stl"
  scale:
    - 1.0
    - 1.0
    - 1.0
  pose_type:
    r:
      - 0.0
      - rad(pi/2)
      - 0.0
    p:
      - 0.0
      - 0.0
      - rad(pi/2)
    z:
      - 0.640
      - 0.683
      - 0.734
    sym_ax_z:
      - false
      - false
      - false
te:
  offset_pos:
    x: 0.0
    y: 0.0
    z: 0.0
  offset_rot:
    r: 0.0
    p: 0.0
    y: 0.0
  model_file: "te_simplified.stl"
  scale:
    - 1.0
    - 1.0
    - 1.0
  pose_type:
    r:
      - 0.0319
      - 0.0
      - 0.0
      - rad(-pi/2)
    p:
      - 0.0275
      - rad(pi/2)
      - rad(-pi/2)
      - 0.0
    z:
      - 0.674
      - 0.7217
      - 0.7137
      - 0.7089
    sym_ax_z:
      - false
      - false
      - false
      - false
tuyau:
  offset_pos:
    x: 0.0
    y: 0.0
    z: 0.0
  offset_rot:
    r: 0.0
    p: 0.0
    y: 0.0
  model_file: "tuyau.stl"
  scale:
    - 1.0
    - 1.0
    - 1.0
  pose_type:
    r:
      - 0.0
      - 0.0
      - -0.0877
    p:
      - rad(pi/2)
      - rad(-pi/2)
      - -0.1070
    z:
      - 0.696
      - 0.701
      - 0.6930
    sym_ax_z:
      - true
      - true
      - false
couvercle:
  offset_pos:
    x: 0.0
    y: 0.0
    z: 0.0
  offset_rot:
    r: 0.0
    p: 0.0
    y: 0.0
  model_file: "couvercle_simplified.stl"
  scale:
    - 1.0
    - 1.0
    - 1.0
  pose_type:
    r:
      - 0.0
      - 0.0
      - -0.1013
    p:
      - rad(pi/2)
      - rad(-pi/2)
      - 0.1587
    z:
      - 0.6746
      - 0.66
      - 0.6944
    sym_ax_z:
      - true
      - true
      - false