Robotiq-2F-140:
  nb-fingers: 2
  finger_1:
    links:
      - /right_spring_link_collision
      - /right_follower_collision
    friction:
      - 0.1
      - 0.1

  finger_2:
    links:
      - /left_spring_link_collision
      - /left_follower_collision
    friction:
      - 0.1
      - 0.1

  palm:
    links:
      - /robotiq
    friction:
      - 0.1
  joints:
    - /right_driver_j
    - /left_driver_j
  limit:
    lower:
      - -90 # Degree
      - -90
    upper:
      - -46
      - -46
  abduction:
    activated:
      - false
      - false
    limit:
      lower:
        - null
        - null
      upper:
        - null
        - null
